config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  ######
  # Home
  root to: "home#index"
  get 'home/index'
  get 'home/about'

  ######
  # Profile
  get 'profile', to: 'profile#profile_home'
  get 'profile/account'
  get 'profile/settings'
  patch 'profile/update'

  ##################
  ####     Resources
  resources :articles do
    member do
      get 'show_card'
      post 'favourite'
    end
  end

  resources :categories

  # resources :products do
  #   resources :magics, controller: "products/magics"
  #   resources :reviews do
  #     member do
  #       get :review
  #     end
  #   end
  #   resources :comments, module: :products

  resources :comments do
    member do
      post 'archive'
    end
  end

  resources :news_letter_subscriptions

  ######
  # Health Check
  get "up" => "rails/health#show", as: :rails_health_check

end

app/models/article.rb
class Article < ApplicationRecord
  has_many :category_article_joins, dependent: :destroy, inverse_of: :article
  has_many :categories, through: :category_article_joins, inverse_of: :articles
  has_many :favourite_articles_joins, dependent: :destroy, inverse_of: :article, class_name: 'FavouritedArticle'

  has_many :comments, as: :commentable, dependent: :destroy
  has_many :archived_comments, -> { where(archived: true) }, as: :commentable, class_name: 'Comment'


  has_rich_text :content
  has_one_attached :card_image

  def get_image_url
    if card_image.attached?
      Rails.application.routes.url_helpers.rails_blob_path(card_image, only_path: true)
    else
      self.categories.to_a.first.get_image_url
    end
  end

  def favourited?

  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :check_user_signed_in?, except: [:index, :show]

  def index
    query = Article.where(archived: false).order(created_at: :desc)
    query = query.joins(:categories).where(categories: { name: params[:category]}) if params[:category].present?

    @pagy, @articles = pagy(query, items: 10)
  end

  def show
    @article = Article.where(archived: false)
      .eager_load(comments: :commenter)
      .where(comments: { archived: false })
      .order(created_at: :desc)
      .find(params[:id])
  end

  def show_card
    @article = Article.find(params[:id])
  end

  def edit
    @article = Article.find(params[:id])
    authorize! :edit, @article
  end

  def update
    @article = Article.find(params[:id])
    authorize! :update, @article

    @article.update(article_params)
    redirect_to article_path(@article)
  end

  def favourite
    @article = Article.left_outer_joins(:favourite_articles_joins)
      .where(favourite_articles_joins: { user: current_user })
      .find_by(id: params[:id])

    return head :no_content unless @article

    authorize! :read, @article

    current_user.favourite_articles << @article unless current_user.favourite_articles.include?(@article)
    redirect_to article_path(@article)
  end

  def destroy; end

  protected

  def article_params
    params.require(:article).permit(:name, :content, :archived, :featured, :category_ids, :card_image)
  end
end

app/helpers/article_helper.rb
module ArticleHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/edit.html.erb
<%= render PrimaryContainerComponent.new do |content| %>
  <% content.capture_content do %>
    <%= turbo_frame_tag "article-#{@article.id}" do %>
      <div class="relative isolate bg-form flex flex-col gap-3 lg:flex-row rounded-xl shadow p-1">
        <!--    Back Button-->
        <%= link_to show_card_article_path(@article), class: "absolute top-5 right-5 rounded-full text-white w-12 h-12  flex justify-center inline-flex items-center justify-center p-4 px-6 py-3 overflow-hidden font-medium text-indigo-600 transition duration-300 ease-out border-2 border-purple-500 rounded-full shadow-md group" do %>
          <span class="absolute inset-0 flex items-center justify-center w-full h-full text-white duration-300 -translate-x-full bg-purple-500 group-hover:translate-x-0 ease">
            Back
          </span>
          <span class="absolute p-3 flex items-center justify-center w-full h-full text-purple-500 transition-all duration-300 transform group-hover:translate-x-full ease">
            <%= image_tag 'svg/left_arrow.svg' %>
          </span>
          <span class="relative invisible"></span>
        <% end %>

        <div class="flex flex-row justify-around w-full">
          <%= form_with(model: @article, url: article_path, method: :patch, local: true, class: "w-full") do |form| %>
            <section class="flex flex-col items-center p-1 mx-2">
              <h1 class="mb-8">Edit Article</h1>

              <div class="w-full flex flex-row gap-5">
                <%= form.label :title %>
                <%= form.text_field :name, class: "text-input" %>
              </div>

              <div class="w-full flex flex-row gap-5 pt-1">
                <%= form.label :image %>
                <%= form.file_field :card_image, class: "text-gray-900 dark:text-gray-300" %>
              </div>

              <div class="w-full  justify-between ">
                <%= form.label :article_content %>
                <%= form.rich_text_area :content, class: "border-2 h-72 border-blue-300" %>
              </div>

              <div class="flex flex-col p-5">
                <%= form.submit "Update Article", class: "btn btn-primary p-2 dark:btn-outline" %>
              </div>
            </section>
          <% end %>
        </div>
      </div>
    <% end %>
  <% end %>
<% end %>

app/views/articles/index.html.erb
<%= render PrimaryContainerComponent.new do |content| %>
  <% content.capture_content do %>
    <% @articles.each do |article| %>
      <div class="my-1">
        <%= render Articles::CardComponent.new(article: article) %>
      </div>
    <% end %>

    <%= render(NewsletterComponent.new) %>
  <% end %>
<% end %>

app/views/articles/show.html.erb
<%= render PrimaryContainerComponent.new do |content| %>
  <% content.capture_content do %>
    <%= render Articles::PageComponent.new(article: @article) %>

    <%= render(NewsletterComponent.new) %>
  <% end %>
<% end %>

app/views/articles/show_card.html.erb
<%= render Articles::CardComponent.new(article: @article) %>